### ISSUE TITLE
Key id

### ISSUE THREAD

**Issue by agostbiro** [itsobvioustech/aa-passkeys-wallet#1]
Hi, 

Thanks for implementing this! I'm wondering where does the key id come from and how is it different from the public key?

Best,
Agost

**Comment by jebu** [comment]
KeyId is generated by the browser which is usually a base64 encoded string. This is the id attribute of PublicKeyCredential as specified [here](https://www.w3.org/TR/webauthn-2/#publickeycredential). Its used as an identifier for the public key and is not the actual public key.

**Comment by agostbiro** [comment]
Thanks!
